# Generated by Django 5.0.7 on 2024-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='problem',
            name='progress',
            field=models.CharField(choices=[('processing', 'Processing'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='problems/'),
        ),
    ]
